=== victorvisus/LMSGI_ProyectoEvaluacion1/victor_visus/ejercicio02_xml/public_html/carreraValida.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Carreras_populares (carreras+)>

    <!ELEMENT carreras (caracteristicas,equipo,recorrido,categorias+,clasificaciones)>
    <!ATTLIST carreras cod_carrera ID #REQUIRED>

     <!-- CARACTERÃSTICAS -->
        <!ELEMENT caracteristicas (fecha,descripcion)>

        <!-- Caracterristicas.fecha -->
            <!ELEMENT fecha EMPTY>
            <!ATTLIST fecha dia CDATA #REQUIRED >
            <!ATTLIST fecha mes (enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) #REQUIRED >
            <!ATTLIST fecha anio CDATA #REQUIRED >
        <!-- Caracteristicas.descripcion -->
            <!ELEMENT descripcion ANY>

      <!--EQUIPO -->
        <!ELEMENT equipo (persona+)>

        <!-- Equipo.personas -->
            <!ELEMENT persona (funcion,nombre,apellido,direccion)>
            <!ATTLIST persona cod_persona ID #REQUIRED>
              <!-- Equipo.personas.funcion -->
                <!ELEMENT funcion EMPTY>
                <!ATTLIST funcion tipo (Juez|Corredor|Organizador|Auxiliar) #REQUIRED>
              <!-- Equipo.personas.nombre -->
                <!ELEMENT nombre (#PCDATA)>
              <!-- Equipo.personas.apellido -->
                <!ELEMENT apellido (#PCDATA)>
              <!-- Equipo.personas.direccion -->
                <!ELEMENT direccion (calle, num, cp, ciudad)>
                    <!ELEMENT calle (#PCDATA)>
                    <!ELEMENT num (#PCDATA)>
                    <!ELEMENT cp (#PCDATA)>
                    <!ELEMENT ciudad (#PCDATA)>


      <!-- RECORRIDO -->
        <!ELEMENT recorrido (longitud,estado)>
        <!ATTLIST recorrido nombre CDATA #REQUIRED>

          <!-- Recorrido.longitud -->
            <!ELEMENT longitud EMPTY>
            <!ATTLIST longitud km CDATA #REQUIRED>
          <!-- Recorrido.estado -->
            <!ELEMENT estado EMPTY>
            <!ATTLIST estado grado (Bueno|Medio|Malo) #REQUIRED>


      <!-- CATEGORIAS -->
        <!ELEMENT categorias (edad_min,edad_max)>
        <!ATTLIST categorias nombre (Benjamin|Alevin|Infantil|Cadete|Juvenil|Senior) #REQUIRED>

          <!-- Categoriass.edad_min -->
            <!ELEMENT edad_min EMPTY>
            <!ATTLIST edad_min edad CDATA #REQUIRED>
          <!-- Categoriass.edad_max -->
            <!ELEMENT edad_max EMPTY>
            <!ATTLIST edad_max edad CDATA #REQUIRED>


      <!-- CLASIFICACIONES -->
        <!ELEMENT clasificaciones (posicion+)>

          <!-- Clasificaciones.posicion -->
            <!ELEMENT posicion (nombre_corredor,tiempo)>
            <!ATTLIST posicion categoria CDATA #REQUIRED>
            <!ATTLIST posicion numero CDATA #REQUIRED>
              <!-- Clasificacion.posicion.nombre_corredor -->
                <!ELEMENT nombre_corredor EMPTY>
                <!ATTLIST nombre_corredor nombre CDATA #REQUIRED>
              <!-- Clasificacion.posicion.tiempo -->
                <!ELEMENT tiempo EMPTY>
                <!ATTLIST tiempo tiempo_min CDATA #REQUIRED>

=== victorvisus/LMSGI_ProyectoEvaluacion1/victor_visus/ejercicio02_xml/public_html/carrera.xml
<?xml version= "1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE Carreras_populares SYSTEM "carreraValida.dtd">

<Carreras_populares>

    <carreras cod_carrera="A10">
        <caracteristicas>
            <fecha dia="12" mes="marzo" anio="2021" />
            <descripcion>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </descripcion>
        </caracteristicas>

        <equipo>
            <persona cod_persona="H20">
                <funcion tipo="Juez"/>
                <nombre>Luis Miguel</nombre>
                <apellido>López</apellido>
                <direccion>
                    <calle>
                        Federico el de los palotes
                    </calle>
                    <num>23</num>
                    <cp>64897</cp>
                    <ciudad>Logroño</ciudad>
                </direccion>
            </persona>
            <persona cod_persona="H25">
                <funcion tipo="Corredor"/>
                <nombre>Juan</nombre>
                <apellido>Dominguez</apellido>
                <direccion>
                    <calle>
                        Rua vieja
                    </calle>
                    <num>15</num>
                    <cp>50222</cp>
                    <ciudad>Zaragoza</ciudad>
                </direccion>
            </persona>
            <persona cod_persona="H35">
                <funcion tipo="Corredor"/>
                <nombre>Angel</nombre>
                <apellido>De la Rosa</apellido>
                <direccion>
                    <calle>
                        de al lado
                    </calle>
                    <num>55</num>
                    <cp>50059</cp>
                    <ciudad>Zaragoza</ciudad>
                </direccion>
            </persona>
        </equipo>

        <recorrido nombre="altamira">
            <longitud km="7"/>
            <estado grado="Bueno" />
        </recorrido>

        <categorias nombre="Juvenil">
            <edad_min edad="16" />
            <edad_max edad="18" />
        </categorias>

        <categorias nombre="Senior">
            <edad_min edad="20" />
            <edad_max edad="80" />
        </categorias>

        <clasificaciones>
            <posicion categoria="Juvenil" numero="1">
                <nombre_corredor nombre="Angel de la Rosa" />
                <tiempo tiempo_min="186" />
            </posicion>
            <posicion categoria="Juvenil" numero="2">
                <nombre_corredor nombre="Luis Miguel López" />
                <tiempo tiempo_min="197" />
            </posicion>
        </clasificaciones>

    </carreras>

</Carreras_populares>
